<div class="home-index-bound">
    <h1>List Category</h1>
    <a href="<?php echo $this->url('category', array('action'=>'add'));?>">
        <button type="button" class="btn btn-success"><span class="glyphicon glyphicon-plus"></span> Add</button>
    </a>
</div>
<table class="table">
    <tr>
        <th>Id</th>
        <th>Description</th>
        <th>Action</th>
    </tr>
    <?php foreach ($listCategory as $category) : ?>
        <tr>
            <td><?php echo $this->escapeHtml($category['id']); ?></td>
            <td><?php echo $this->escapeHtml($category['description']); ?></td>
            <td>
                <a href="<?php echo $this->url('category', array('action'=>'edit', 'id' => $category['id']));?>">Edit</a>
                <span>|</span>
                <a href="<?php echo $this->url('category', array('action'=>'delete', 'id' => $category['id']));?>">Delete</a>
            </td>
        </tr>
    <?php endforeach; ?>
</table>