<?php
$title = 'Add new book';
$this->headTitle($title);
?>
    <h1><?php echo $this->escapeHtml($title); ?></h1>
<?php

$form = $this->form;
$form->setAttribute('action', $this->url('book', array('action' => 'add')));
$form->prepare();

$form->add(array(
    'type' => 'Zend\Form\Element\Select',
    'name' => 'category',
    'options' => array(
        'label'         => 'Category',
        'value_options' => $this->listCategory,
    )
));

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('book_id'));
echo $this->formRow($form->get('title'));
echo $this->formRow($form->get('category'));
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();